---
title: "analyze_data"
output: html_document
date: "2024-01-26"
---

```{r}
# Optionnel, pour charger la base si déjà enregistrée.
# pres1981 <- read_feather("data/pres1981.feather")
```

```{r}
# Variables totales
nb_communes <- uniqueN(pres1981, by = "codecommune")
# La population des communes présente de nombreuses données manquantes. Pour connaître la population totale, utilisons plutôt les estimations de l'Insee : https://www.insee.fr/fr/statistiques/serie/000067670
pop_tot_1981 <- 54028630
```


# Analyses descriptives


```{r}
# Initialisation et calcul des valeurs
stat_desc <- data.table()
for (col in names(pres1981)) {if (!(col %in% c("dep", "codecommune", "codecommune2"))) {
  summary <- pres1981[, {
    fivenum_values <- fivenum(get(col))
    nan_count <- sum(is.na(get(col)))
    nan_count_prop <- round(100 * nan_count / nb_communes, 2)
    nan_pop <- sum(pop1981[is.na(get(col))], na.rm = TRUE)
    prop_nan_pop <- round(100 * nan_pop / pop_tot_1981, 2)
    data.table(
      Variable = col,
      "Min" = round(fivenum_values[1], 0),
      "1er quartile" = fivenum_values[2],
      "Mediane" = fivenum_values[3],
      "3e quartile" = fivenum_values[4],
      "Max" = fivenum_values[5],
      "Valeurs manquantes" = nan_count,
      "En % des communes" = nan_count_prop,
      "En % de la population" = prop_nan_pop
    )
  }]
stat_desc <- rbind(stat_desc, summary)
}}

# Simplification des valeurs et enregistrement du tableau
stat_desc[] <- lapply(stat_desc, round_and_remove_zeros)
print(xtable(stat_desc, type = "latex"), file = "output/stat_desc.tex")
print(stat_desc)

# Nettoyage
rm(stat_desc, summary)
```

```{r}
# Calcul du taux agrégé de propriétaires
propri_tot <- data.table(year = numeric(), sum_npropri = numeric(), sum_nlogement = numeric(), prop_ratio = numeric())
for (year in 1960:2022) {
  col_npropri <- paste0("npropri", year)
  col_nlogement <- paste0("nlogement", year)
  sum_npropri <- sum(propri[[col_npropri]], na.rm = TRUE)
  sum_nlogement <- sum(propri[[col_nlogement]], na.rm = TRUE)
  prop_ratio <- sum_npropri / sum_nlogement
  propri_tot <- rbind(propri_tot, data.table(year = year, sum_npropri = sum_npropri, sum_nlogement = sum_nlogement, prop_ratio = prop_ratio))
}

# Graph
ggplot(propri_tot, aes(x = year, y = prop_ratio)) +
  geom_line(color = "skyblue") +
  geom_point(color = "skyblue") +
  labs(title = "Taux de propriétaires, 1960-2022",
       x = "Années",
       y = "Taux de propriétaires") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

# Nettoyage
rm(col_npropri, col_nlogement, sum_npropri, sum_nlogement, prop_ratio, propri_tot, year)
```


# Régressions


```{r}
# Nan cumulées, en vue des analyses multivariées
columns <- names(pres1981)[names(pres1981) != "pop1981"]

na_pop <- list()
na_count <- list()

for (col in columns) {
  na_count[[col]] <- sum(is.na(pres1981[[col]]))
  na_pop[[col]] <- pres1981[is.na(get(col)), sum(pop1981, na.rm = TRUE)]
}

na_pop <- data.table(variable = names(na_pop), missing_pop = unlist(na_pop))
na_count <- data.table(variable = names(na_count), missing_communes = unlist(na_count))

nan_results <- merge(na_pop, na_count, by = "variable")

nb_communes <- uniqueN(pres1981, by = "codecommune")
nan_results[, prop_missing_communes := 100 * missing_communes / nb_communes]

pop_tot_1981 <- 54 028 630
nan_results[, prop_missing_pop := 100 * missing_pop / pop_tot_1981]

print(nan_results)
print(xtable(nan_results, type = "latex"), file = "output/nan_results.tex")

rm(columns, na_pop, na_count)
```

```{r}
dependent_variable <- "part"
excluded_covariables <- c("dep", "codecommune", "plm", "abs", "nulsT2", "absT2", "codecommune2", "dep2", "part", "partT2", "GD_ratio_T1", "GD_ratio_T2", "lib_ratio_T1")
regression_formula <- as.formula(paste(dependent_variable, "~", paste(setdiff(names(pres1981), excluded_covariables), collapse = "+")))
model <- lm(regression_formula, data = pres1981)
summary(model)

prop_missing_communes_1981 <- 100 * sum(apply(pres1981[, !excluded_covariables, with = FALSE], 1, function(row) any(is.na(row)))) / nb_communes
rows_with_nan <- pres1981[apply(pres1981[, !excluded_covariables, with = FALSE], 1, function(row) any(is.na(row))), ]
prop_missing_pop_1981 <- 100 * sum(rows_with_nan$pop1981, na.rm = TRUE) / pop_tot_1981
cat("Les valeurs manquantes représentent", prop_missing_communes_1981, "% des communes et", prop_missing_pop_1981, "% de la population en 1981.")

rm(dependent_variable, excluded_covariables, regression_formula)
```

```{r}
dependent_variable <- "GD_ratio_T1"
excluded_covariables <- c("dep", "codecommune", "plm", "abs", "nulsT2", "absT2", "codecommune2", "dep2", "part", "partT2", "GD_ratio_T1", "GD_ratio_T2", "lib_ratio_T1")
regression_formula <- as.formula(paste(dependent_variable, "~", paste(setdiff(names(pres1981), excluded_covariables), collapse = "+")))
model <- lm(regression_formula, data = pres1981)
summary(model)

prop_missing_communes_1981 <- 100 * sum(apply(pres1981[, !excluded_covariables, with = FALSE], 1, function(row) any(is.na(row)))) / nb_communes
rows_with_nan <- pres1981[apply(pres1981[, !excluded_covariables, with = FALSE], 1, function(row) any(is.na(row))), ]
prop_missing_pop_1981 <- 100 * sum(rows_with_nan$pop1981, na.rm = TRUE) / pop_tot_1981
cat("Les valeurs manquantes représentent", prop_missing_communes_1981, "% des communes et", prop_missing_pop_1981, "% de la population en 1981.")

rm(dependent_variable, excluded_covariables, regression_formula)
```
