# Panel

```{r}
panel_data <- load_parquet("data_main/panel_data.parquet")
```

## Analyse des valeurs manquantes

Tableau présentant le nombre de NA par variable et par an, coloré façon corrélogramme.

## Analyses descriptives

Evolution historique des principaux outcomes et du taux de propriétaires ?

```{r}
# Exemple grossier avec la participation au premier tour

# Calculate the average of part_T1 for each year
avg_part_T1 <- aggregate(part_T1 ~ year, data = panel_data, FUN = mean)

# Plot the evolution of the average of part_T1 over time
ggplot(avg_part_T1, aes(x = year, y = part_T1)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Average part_T1", title = "Participation au premier tour des élections présidentielles, 1965-2022")
```

Cartes ?

## Panel...

```{r}
# On convertit les données aux format pdata et on sélectionne les régresseurs
panel_as_pdata <- pdata.frame(panel_data, index = c("codecommune", "year"))
regressors <- c("ppropri", "popcomm", "popagglo", "pinscript", "age", "prop1539", "prop4059", "prop60p", "propf", "propbac", "propsup", "pagri", "pindp", "pcadr", "ppint", "pempl", "pchom", "petranger", "revmoy")
## Régresseurs abandonnés pour éviter la colinéarité : prop014, propnodip, pouvr

# On ajuste le modèle pour les ratios relatifs = sur exprimés
## Possibilité d'utiliser within comme paramètre et d'éliminer le clustering.
relative_outcomes <- c("part_T1", "part_T2", "GD_ratio_T1", "GD_ratio_T2", "EC_ratio_T1", "EC_ratio_T2")
relative_results <- list()
for (outcome in relative_outcomes) {
  regression_formula <- as.formula(paste(outcome, "~", paste(regressors, collapse = "+")))
  model_name <- paste0(outcome, "_model")
  relative_results[[model_name]] <- plm(regression_formula, data = panel_as_pdata, model = "fd", cluster = "dep")
}
stargazer(relative_results, type = "html", out = "output/panel_relative_results.html")

# On ajuste le modèle pour les ratios relatifs = sur inscrits
absolute_outcomes <- c("part_T1", "part_T2", "GIns_ratio_T1", "DIns_ratio_T1", "GIns_ratio_T2", "DIns_ratio_T2", "EIns_ratio_T1", "CIns_ratio_T1", "EIns_ratio_T2", "CIns_ratio_T2")
absolute_results <- list()
for (outcome in absolute_outcomes) {
  regression_formula <- as.formula(paste(outcome, "~", paste(regressors, collapse = "+")))
  model_name <- paste0(outcome, "_model")
  absolute_results[[model_name]] <- plm(regression_formula, data = panel_as_pdata, model = "fd", cluster = "dep")
}
stargazer(absolute_results, type = "html", out = "output/panel_absolute_results.html")



# Exprimer les habitants et les revenus en milliers pour simplifier la lecture ?
```

# **ACP**

```{r}
acp_data <- load_parquet("acp_data/panel_data.parquet")
```

## Analyse des valeurs manquantes

## Analyses descriptives

Corrélogramme

Cartes ?

## ACP...
