---
title: "map_data"
output: html_document
date: "2024-01-29"
---

```{r}
# Téléchargement du fond de carte
if (!dir.exists("shapefile")) {dir.create("shapefile")}
httr::GET("https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS_SHP_TERRITOIRES_PACK_2023-12-19$ADMIN-EXPRESS_3-2__SHP_LAMB93_FXX_2023-12-19/file/ADMIN-EXPRESS_3-2__SHP_LAMB93_FXX_2023-12-19.7z", timeout(1800), progress(), write_disk("shapefile/Carto_Insee.7z", overwrite = TRUE))

# Extraction
root_name <- ("ADMIN-EXPRESS_3-2__SHP_LAMB93_FXX_2023-12-19/ADMIN-EXPRESS/1_DONNEES_LIVRAISON_2023-12-00156/ADE_3-2_SHP_LAMB93_FXX-ED2023-12-19/")
file_names <- c("COMMUNE", "ARRONDISSEMENT_MUNICIPAL")
extensions <- c("shp", "shx", "dbf")

files_to_extract <- c()
for (file_name in file_names) {
  for (extension in extensions) {
    files_to_extract <- c(files_to_extract, paste0(root_name, file_name, ".", extension))
  }
}

archive_extract("shapefile/Carto_Insee.7z", dir = "shapefile", files = files_to_extract)

# Nettoyage
root_path <- file.path("shapefile", "ADMIN-EXPRESS_3-2__SHP_LAMB93_FXX_2023-12-19", "ADMIN-EXPRESS", "1_DONNEES_LIVRAISON_2023-12-00156", "ADE_3-2_SHP_LAMB93_FXX-ED2023-12-19")

for (file_name in file_names) {
  for (ext in extensions) {
    source_file <- file.path(root_path, paste0(file_name, ".", ext))
    target_file <- file.path("shapefile", paste0(file_name, ".", ext))
    file.rename(source_file, target_file)
  }
}

unlink(c("shapefile/Carto_Insee.7z", "shapefile/ADMIN-EXPRESS_3-2__SHP_LAMB93_FXX_2023-12-19"), recursive = TRUE)
rm(ext, extension, extensions, file_name, file_names, files_to_extract, root_name, root_path, source_file, target_file)
```

```{r}
# Construction de la base
background_province <- st_read("shapefile/COMMUNE.shx")
map_data_province <- merge(background_province, subset(pres1981, dep != 75), by.x = "INSEE_COM", by.y = "codecommune", all.x = TRUE)
map_data_province <- subset(map_data_province, select = -c(INSEE_ARR, INSEE_CAN, INSEE_DEP, INSEE_REG, SIREN_EPCI, STATUT))

background_paris <- st_read("shapefile/ARRONDISSEMENT_MUNICIPAL.shx")
map_data_paris <- merge(background_paris, subset(pres1981, dep == 75), by.x = "INSEE_ARM", by.y = "codecommune", all.x = TRUE)
map_data_paris <- subset(map_data_paris, select = -INSEE_ARM)

map_data <- rbind(map_data_province, map_data_paris)
st_crs(map_data) <- 9794

rm(background_province, map_data_province, background_paris, map_data_paris)
```

```{r}
# st_write(map_data, "data/map.gpkg", driver = "GPKG", append = TRUE)
# unlink("shapefile", recursive = TRUE)
```

# Cartes statiques

```{r}
# map_data <- st_read("data/map.gpkg")
```

```{r}
# Carte statique avec ggplot, réduite à un département pour améliorer la lisibilité et accélérer le rendu, à résolution paramétrable
selected_dep <- "25"
subset_map_data <- map_data[map_data$dep == selected_dep, ]
subset_map_data$part <- round(subset_map_data$part, 2)
title <- paste0("Participation au premier tour des élections présidentielles\n\ndépartement = ", selected_dep, "\nannée = 1981")
output_file <- paste0("output/part_1981_dep", selected_dep, ".png")

# Calcul des dimensions de la carte
bbox <- st_bbox(subset_map_data)
aspect_ratio <- diff(c(bbox$xmin, bbox$xmax)) / diff(c(bbox$ymin, bbox$ymax))
base_width <- 7 # Paramètre définissant la résolution
base_height <- base_width / aspect_ratio
font_size <- base_width * 2.2

# Génération de la carte
plot <- ggplot() +
  geom_sf(data = subset_map_data, aes(fill = part)) +
  scale_fill_viridis_c(name = "Participation", labels = scales::percent_format(scale = 1)) +
  ggtitle(paste(title)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = font_size),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.title.position = "plot",
        legend.title = element_text(size = font_size * 0.8),
        legend.text = element_text(size = font_size * 0.7))

# Enregistrement de la carte
ggsave(output_file, plot = plot, width = base_width, height = base_height, units = "in")

rm(bbox, aspect_ratio, base_height, base_width, font_size, selected_dep, subset_map_data, title)
```

```{r}
# Carte statique avec ggplot, France entière, à résolution paramétrable
map_data$part <- round(map_data$part, 2)

# Calcul des dimensions de la carte
bbox <- st_bbox(map_data)
aspect_ratio <- diff(c(bbox$xmin, bbox$xmax)) / diff(c(bbox$ymin, bbox$ymax))
base_width <- 7 # Paramètre définissant la résolution
base_height <- base_width / aspect_ratio
font_size <- base_width * 2.2

# Génération de la carte
plot <- ggplot() +
  geom_sf(data = map_data, aes(fill = part)) +
  scale_fill_viridis_c(name = "Participation", labels = scales::percent_format(scale = 1)) +
  ggtitle("Participation au premier tour des élections présidentielles\n1981") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = font_size),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.title.position = "plot",
        legend.title = element_text(size = font_size * 0.8),
        legend.text = element_text(size = font_size * 0.7))

# Enregistrement de la carte
ggsave("part_1981_France.png", plot = plot, width = base_width, height = base_height, units = "in")

rm(bbox, aspect_ratio, base_height, base_width, font_size)
```

# Cartes dynamiques

```{r}
# Carte dynamique avec mapview, réduite à un département (les détails s'affichent en cliquant sur une commune).
subset_map_data <- map_data[map_data$dep == "2A", ]
subset_map_data$rounded_part <- paste0(round(100 * subset_map_data$part, digits = 2), " %")

popup_content <- paste("<strong>Commune</strong>", subset_map_data$NOM, sep = "<br>",
                       "<strong>Participation</strong>", subset_map_data$rounded_part, ""
                       )

mapview(subset_map_data, zcol = "rounded_part", popup = popup_content, layer.name = "Participation T1 1981")

rm(subset_map_data, popup_content)
```

```{r}
# Carte dynamique avec mapview (les détails s'affichent en cliquant sur une commune).
# Ne parvient jamais à se charger complètement, demande trop de ressources ?
map_data$rounded_part <- paste0(round(100 * map_data$part, digits = 2), " %")

popup_content <- paste("<strong>Commune</strong>", map_data$NOM, sep = "<br>",
                       "<strong>Participation</strong>", map_data$rounded_part, ""
                       )

mapview(map_data, zcol = "rounded_part", popup = popup_content, layer.name = "Participation T1 1981")

rm(subset_map_data, popup_content)
```
