
```{r}
# Préparation : sélection des variables, suppression des valeurs manquantes et création d'indicatrices pour les types de communes (car l'argument quali.sup donne des résultats étranges)
variables_of_interest <- c(mca_detailed_outcomes, full_mca_regressors)
mca_data_subset <- detailed_mca_data[, ..variables_of_interest]

mca_data_subset <- na.omit(mca_data_subset)

mca_data_subset$type_comm <- as.factor(mca_data_subset$type_comm)
dummies <- model.matrix(~ type_comm - 1, data = mca_data_subset)
colnames(dummies) <- paste0("type_comm_", 1:ncol(dummies))
mca_data_subset <- cbind(mca_data_subset, dummies)
mca_data_subset$type_comm <- NULL

# Analyse
quant_regressors <- setdiff(full_mca_regressors, "type_comm")
quant_regressors <- c(quant_regressors, "type_comm_1", "type_comm_2", "type_comm_3", "type_comm_4")
result <- PCA(mca_data_subset, scale.unit = TRUE, quanti.sup=quant_regressors, ncp = 10, graph = FALSE)

# Résultats
## Histogramme de la contribution des axes à la variance totale
screeplot <- fviz_screeplot(result, addlabels = TRUE, ylim = c(0, 30), title = "Histogramme de l'inertie totale") + theme_gray()
screeplot$layers[[1]]$aes_params$fill <- "lightskyblue"
screeplot$layers[[1]]$aes_params$colour <- "cornflowerblue"
screeplot$layers[[2]]$aes_params$colour <- "darkblue"
screeplot$layers[[3]]$aes_params$colour <- "darkblue"
screeplot$layers[[4]]$aes_params$colour <- "darkblue"
screeplot$theme$plot.title$hjust <- 0.5
screeplot$labels$x <- "Dimensions"
screeplot$labels$y <- "% de variance expliquée"
screeplot
ggsave("output_transversal/screeplot_ACP1.png", plot = screeplot, width = 10, height = 6, units = "in", dpi = 300)

## Contribution des variables aux axes (comportements électoraux seulement)
## Correspond à la qualité de représentation des variables (= cos2) normalisée entre 1 et 100
## Présentable à l'aide d'un tableau...
coeffs <- result$var$contrib
labels <- rownames(result$var$contrib)
axis_df <- data.frame(labels, coeffs, row.names = NULL)
colnames(axis_df) <- c("Variables", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
axis_tbl <- axis_df %>%
  gt() %>%
  fmt_number(decimals = 2, drop_trailing_zeros = TRUE) %>%
  tab_header("Contribution des variables à l'inertie des axes", subtitle = NULL, preheader = NULL) %>%
  tab_spanner(label = "Axes", columns = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"), id = "axes") %>%
  data_color(method = "numeric", columns = !matches("Variables"), palette ="Oranges", ) %>%
  tab_style(
    style = cell_text(align = "center"),
    locations = list(
      cells_column_labels(columns = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")),
      cells_body(columns = !matches("Variables")))) %>%
  tab_style(
    style = cell_fill(color = "lightgrey"),
    locations = cells_column_labels(columns = c("1", "3", "5", "7", "9"))) 
axis_tbl
gtsave(axis_tbl, filename = "contrib_axes_acp1.tex", path = "output_transversal")

## ... ou d'un corrplot
corrplot(result$var$contrib, title = "Contribution des variables à l'inertie des axes", is.corr = FALSE, col.lim = c(0, 100), mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)

## Corrélation des variables aux axes
## Avec à nouveau deux représentations possibles...
## Des corrplots
corrplot(result$var$coord[, 1:3], title = "Corrélation des outcomes aux axes", is.corr = TRUE, mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)
corrplot(result$quanti.sup$coord[, 1:3], title = "Corrélation des régresseurs aux axes", is.corr = TRUE, mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)
## Des projections sur les plans factoriels
plot.PCA(result, axes = c(1,2), choix = "var", select = "cos2 7", title = "Projection sur les axes 1 et 2")
plot.PCA(result, axes=c(1,3), choix="var", select = "cos2 7", title = "Projection sur les axes 1 et 3")
plot.PCA(result, axes=c(2,3), choix="var", select = "cos2 7", title = "Projection sur les axes 2 et 3")

## Qualité de représentation des variables
corrplot(result$var$cos2[, 1:3], title = "Qualité de représentation des variables électorales", is.corr = FALSE, col.lim = c(0, 1), mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)
corrplot(result$quanti.sup$cos2[, 1:3], title = "Qualité de représentation des régresseurs", is.corr = FALSE, col.lim = c(0, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)

# Nettoyage
rm(axis_df, axis_tbl, coeffs, dummies, labels, mca_data_subset, quant_regressors, result, variables_of_interest, screeplot)
```

```{r}
# Préparation : sélection des variables, suppression des valeurs manquantes et création d'indicatrices pour les types de communes (car l'argument quali.sup donne des résultats étranges)
variables_of_interest <- c(mca_detailed_outcomes, full_mca_regressors)
mca_data_subset <- detailed_mca_data[, ..variables_of_interest]

mca_data_subset <- na.omit(mca_data_subset)

mca_data_subset$type_comm <- as.factor(mca_data_subset$type_comm)
dummies <- model.matrix(~ type_comm - 1, data = mca_data_subset)
colnames(dummies) <- paste0("type_comm_", 1:ncol(dummies))
mca_data_subset <- cbind(mca_data_subset, dummies)
mca_data_subset$type_comm <- NULL

# Analyse
result <- PCA(mca_data_subset, scale.unit = TRUE, ncp = 10, graph = FALSE)

# Résultats
## Histogramme de la contribution des axes à la variance totale
screeplot <- fviz_screeplot(result, addlabels = TRUE, ylim = c(0, 30), title = "Histogramme de l'inertie totale") + theme_gray()
screeplot$layers[[1]]$aes_params$fill <- "lightskyblue"
screeplot$layers[[1]]$aes_params$colour <- "cornflowerblue"
screeplot$layers[[2]]$aes_params$colour <- "darkblue"
screeplot$layers[[3]]$aes_params$colour <- "darkblue"
screeplot$layers[[4]]$aes_params$colour <- "darkblue"
screeplot$theme$plot.title$hjust <- 0.5
screeplot$labels$x <- "Dimensions"
screeplot$labels$y <- "% de variance expliquée"
screeplot
ggsave("output_transversal/screeplot_ACP2.png", plot = screeplot, width = 10, height = 6, units = "in", dpi = 300)

## Contribution des variables aux axes (comportements électoraux seulement)
## Correspond à la qualité de représentation des variables (= cos2) normalisée entre 1 et 100
## Présentable à l'aide d'un tableau...
coeffs <- result$var$contrib
labels <- rownames(result$var$contrib)
axis_df <- data.frame(labels, coeffs, row.names = NULL)
colnames(axis_df) <- c("Variables", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
axis_tbl <- axis_df %>%
  gt() %>%
  fmt_number(decimals = 2, drop_trailing_zeros = TRUE) %>%
  tab_header("Contribution des variables à l'inertie des axes", subtitle = NULL, preheader = NULL) %>%
  tab_spanner(label = "Axes", columns = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"), id = "axes") %>%
  data_color(method = "numeric", columns = !matches("Variables"), palette ="Oranges", ) %>%
  tab_row_group(label = "Outcomes", rows = 1:15, id = "out") %>%
  tab_row_group(label = "Régresseurs", rows = 16:44, id = "reg") %>%
  row_group_order(groups = c("out", "reg")) %>%
  tab_style(
    style = list(
      cell_fill(color = "lightgrey"),
      cell_text(style = "italic", align = "center")),
    locations = cells_row_groups(groups = c("out", "reg"))) %>%  
  tab_style(
    style = cell_text(align = "center"),
    locations = list(
      cells_column_labels(columns = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")),
      cells_body(columns = !matches("Variables")))) %>%
  tab_style(
    style = cell_fill(color = "lightgrey"),
    locations = cells_column_labels(columns = c("1", "3", "5", "7", "9"))) 
axis_tbl
gtsave(axis_tbl, filename = "contrib_axes_acp2.tex", path = "output_transversal")

## ... ou d'un corrplot
corrplot(result$var$contrib, title = "Contribution des variables à l'inertie des axes", is.corr = FALSE, col.lim = c(0, 100), mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)
png("output_transveral/contrib_axes_acp2.png")
corrplot(result$var$contrib, title = "Contribution des variables à l'inertie des axes", is.corr = FALSE, col.lim = c(0, 100), mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)
dev_off()

## Corrélation des variables aux axes
## Avec à nouveau deux représentations possibles...
## Des corrplots
corrplot(result$var$coord[1:15, 1:3], title = "Corrélation des outcomes aux axes", is.corr = TRUE, mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)
corrplot(result$var$coord[16:44, 1:3], title = "Corrélation des régresseurs aux axes", is.corr = TRUE, mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)
## Des projections sur les plans factoriels
plot.PCA(result, axes = c(1,2), choix = "var", select = "cos2 13", title = "Projection sur les axes 1 et 2")
plot.PCA(result, axes=c(1,3), choix="var", select = "cos2 13", title = "Projection sur les axes 1 et 3")
plot.PCA(result, axes=c(2,3), choix="var", select = "cos2 13", title = "Projection sur les axes 2 et 3")

## Qualité de représentation des variables
corrplot(result$var$cos2[1:15, 1:3], title = "Qualité de représentation des outcomes", is.corr = FALSE, col.lim = c(0, 1), mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)
corrplot(result$var$cos2[16:44, 1:3], title = "Qualité de représentation des régresseurs", is.corr = FALSE, col.lim = c(0, 1), mar = c(1, 1, 1.5, 1), tl.col = "darkgrey", tl.srt = 45, cl.align.text = "l", cl.cex = 0.7, cl.ratio = 0.3)

# Nettoyage
rm(axis_df, axis_tbl, coeffs, dummies, labels, mca_data_subset, result, variables_of_interest, screeplot)
```
