**Desc**

Graph du taux de participation au T1...


```{r}
# Optionnel, pour charger la base si déjà enregistrée.
panel_data <- load_parquet("data_main/panel_data.parquet")

pres1981 <- subset(panel_data, year == 2017)
```

```{r}
# Variables de référence
nb_communes <- uniqueN(pres1981, by = "codecommune")
# La population des communes présente de nombreuses données manquantes. Pour connaître la population totale, utilisons plutôt les estimations de l'Insee : https://www.insee.fr/fr/statistiques/serie/000067670
pop_tot_1981 <- 54028630
```

# Analyses descriptives

```{r}
# Initialisation et calcul des valeurs
stat_desc <- data.table()
for (col in names(pres1981)) {if (!(col %in% c("dep", "codecommune", "codecommune2"))) {
  summary <- pres1981[, {
    fivenum_values <- fivenum(get(col))
    nan_count <- sum(is.na(get(col)))
    nan_count_prop <- round(100 * nan_count / nb_communes, 2)
    nan_pop <- sum(popcomm[is.na(get(col))], na.rm = TRUE)
    prop_nan_pop <- round(100 * nan_pop / pop_tot_1981, 2)
    data.table(
      Variable = col,
      "Min" = round(fivenum_values[1], 0),
      "1er quartile" = fivenum_values[2],
      "Mediane" = fivenum_values[3],
      "3e quartile" = fivenum_values[4],
      "Max" = fivenum_values[5],
      "Valeurs manquantes" = nan_count,
      "En % des communes" = nan_count_prop,
      "En % de la population" = prop_nan_pop
    )
  }]
stat_desc <- rbind(stat_desc, summary)
}}

# Simplification des valeurs et enregistrement du tableau
stat_desc[] <- lapply(stat_desc, round_and_remove_zeros)
print(xtable(stat_desc, type = "latex"), file = "output/stat_desc.tex")
print(stat_desc)

# Nettoyage
rm(stat_desc, summary)
```

```{r}
# Calcul du taux agrégé de propriétaires
propri <- load_parquet("Proprietaires/proprietairescommunes.parquet")

propri_tot <- data.table(year = numeric(), sum_npropri = numeric(), sum_nlogement = numeric(), prop_ratio = numeric())
for (year in 1960:2022) {
  col_npropri <- paste0("npropri", year)
  col_nlogement <- paste0("nlogement", year)
  sum_npropri <- sum(propri[[col_npropri]], na.rm = TRUE)
  sum_nlogement <- sum(propri[[col_nlogement]], na.rm = TRUE)
  prop_ratio <- sum_npropri / sum_nlogement
  propri_tot <- rbind(propri_tot, data.table(year = year, sum_npropri = sum_npropri, sum_nlogement = sum_nlogement, prop_ratio = prop_ratio))
}

# Graph
plot <- ggplot(propri_tot, aes(x = year, y = prop_ratio)) +
  geom_line(color = "skyblue") +
  geom_point(color = "skyblue") +
  labs(title = "Proportion de propriétaires, 1960-2022",
       x = "Année",
       y = "Proportion de propriétaires") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

print(plot)
ggsave("output/ppropri_1960_2022.png", plot, width = 8, height = 6, dpi = 300)

# Nettoyage
rm(col_npropri, col_nlogement, propri, sum_npropri, sum_nlogement, prop_ratio, propri_tot, year, plot)
```

# Régressions

```{r}
dependent_variable <- "part"
excluded_covariables <- c("dep", "codecommune", "abs", "absT2", "codecommune2", "part", "partT2", "GD_ratio_T1", "GD_ratio_T2", "lib_ratio_T1")
regression_formula <- as.formula(paste(dependent_variable, "~", paste(setdiff(names(pres1981), excluded_covariables), collapse = "+")))
model_part <- lm(regression_formula, data = pres1981)
summary(model_part)

# writeLines(capture.output(summary(model_part)), "output/regression_summary_part.txt")

prop_missing_communes_1981 <- 100 * sum(apply(pres1981[, !excluded_covariables, with = FALSE], 1, function(row) any(is.na(row)))) / nb_communes
rows_with_nan <- pres1981[apply(pres1981[, !excluded_covariables, with = FALSE], 1, function(row) any(is.na(row))), ]
prop_missing_pop_1981 <- 100 * sum(rows_with_nan$pop1981, na.rm = TRUE) / pop_tot_1981
cat("Les valeurs manquantes représentent", prop_missing_communes_1981, "% des communes et", prop_missing_pop_1981, "% de la population en 1981.")

rm(dependent_variable, excluded_covariables, regression_formula)
```

```{r}
dependent_variable <- "GD_ratio_T1"
excluded_covariables <- c("dep", "codecommune", "abs", "absT2", "codecommune2", "part", "partT2", "GD_ratio_T1", "GD_ratio_T2", "lib_ratio_T1")
regression_formula <- as.formula(paste(dependent_variable, "~", paste(setdiff(names(pres1981), excluded_covariables), collapse = "+")))
model_GD_ratio_T1 <- lm(regression_formula, data = pres1981)
summary(model_GD_ratio_T1)

# writeLines(capture.output(summary(model_GD_ratio_T1)), "output/regression_summary_GD_ratio_T1.txt")

prop_missing_communes_1981 <- 100 * sum(apply(pres1981[, !excluded_covariables, with = FALSE], 1, function(row) any(is.na(row)))) / nb_communes
rows_with_nan <- pres1981[apply(pres1981[, !excluded_covariables, with = FALSE], 1, function(row) any(is.na(row))), ]
prop_missing_pop_1981 <- 100 * sum(rows_with_nan$pop1981, na.rm = TRUE) / pop_tot_1981
cat("Les valeurs manquantes représentent", prop_missing_communes_1981, "% des communes et", prop_missing_pop_1981, "% de la population en 1981.")

rm(dependent_variable, excluded_covariables, regression_formula)
```

```{r}
models_list <- list(model_part, model_GD_ratio_T1)
stargazer(models_list, type = "text", out = "output/regression_results.txt")
```

# Corrélogramme

```{r}
install.packages("corrplot")
library(corrplot)

pres1981 <- load_parquet("pres1981.parquet")

prefixes_to_drop <- c("exprimes", "inscrits", "nom", "nul", "pervote", "ppar", "pvoix", "pvote", "voix", "vot")
pres1981 <- pres1981[, .SD, .SDcols = setdiff(names(pres1981), grep(paste0("^", paste(prefixes_to_drop, collapse = "|")), names(pres1981), value = TRUE))]
pres1981 <- pres1981[, -c("plm", "dep2", "plmdoublon", "perpar", "year")]

pres1981 <- pres1981[, -c("part", "partT2", "lib_ratio_T1", "popagglo1981", "prop0141981", "pclerge1791", "prefract1791", "pclerge1856", "pmessalisants1950", "age1981")]

pres1981_numeric <- pres1981[, .SD, .SDcols = sapply(pres1981, is.numeric)]
pres1981_numeric <- pres1981_numeric[complete.cases(pres1981_numeric)]

correlation_matrix <- cor(pres1981_numeric)

png(filename = "output/corrplot.png", width = 2200, height = 1800)
corrplot(
  correlation_matrix,
  type = "upper",
  method = "color",
  col = colorRampPalette(c("blue", "white", "red"))(100),
#  order = "FPC",
  tl.cex = 3.5,
  tl.srt = 60,
  tl.col = "darkgrey",
  cl.cex = 3.5
)
dev.off()
```

