**Cartes statiques**

```{r}
# Carte statique avec ggplot, réduite à une région, à résolution paramétrable
## Se référer à la base code_region pour connaître les numéros de régions

year <- 1965
map_data <- create_map_data(year)

mapped_var <- "part_T1"
mapped_var_name <- "Participation"
selected_reg <- "53"

subset_map_data <- map_data[map_data$INSEE_REG == selected_reg, ]
subset_map_data[[mapped_var]] <- round(subset_map_data[[mapped_var]], 2)
reg_name <- codes_regions$LIBELLE[codes_regions$REG == selected_reg]
reg_abrv <- codes_regions$ABRV[codes_regions$REG == selected_reg]

title <- paste0(mapped_var_name, "\nPremier tour des élections présidentielles\n", reg_name, ", ", year)
output_file <- paste0("output/", mapped_var, "_", year, "_", reg_abrv, ".png")

# Calcul des dimensions de la carte
bbox <- st_bbox(subset_map_data)
aspect_ratio <- diff(c(bbox$xmin, bbox$xmax)) / diff(c(bbox$ymin, bbox$ymax))
base_width <- 7 # Paramètre définissant la résolution
base_height <- base_width / aspect_ratio
font_size <- base_width * 2.2

# Génération de la carte
plot <- ggplot() +
  geom_sf(data = subset_map_data, aes(fill = .data[[mapped_var]])) +
  scale_fill_viridis_c(name = mapped_var_name, labels = scales::percent_format(scale = 100)) +
  ggtitle(paste(title)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = font_size),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.title.position = "plot",
        legend.title = element_text(size = font_size * 0.8),
        legend.text = element_text(size = font_size * 0.7))

# Enregistrement et nettoyage
ggsave(output_file, plot = plot, width = base_width, height = base_height, units = "in")
rm(bbox, aspect_ratio, base_height, base_width, font_size, mapped_var, mapped_var_name, reg_abrv, reg_name, output_file, selected_reg, subset_map_data, title)
```

```{r}
# Carte statique avec ggplot, France entière, à résolution paramétrable

year <- 1965
map_data <- create_map_data(year)
st_write(map_data, "your_shapefile.shp")

mapped_var <- "part_T1"
mapped_var_name <- "Participation"

title <- paste0(mapped_var_name, "\nPremier tour des élections présidentielles\n", year)
output_file <- paste0("output/", mapped_var, "_", year, "_France.png")
map_data[[mapped_var]] <- round(map_data[[mapped_var]], 2)

# Calcul des dimensions de la carte
bbox <- st_bbox(map_data)
aspect_ratio <- diff(c(bbox$xmin, bbox$xmax)) / diff(c(bbox$ymin, bbox$ymax))
base_width <- 7 # Paramètre définissant la résolution
base_height <- base_width / aspect_ratio
font_size <- base_width * 2.2

# Génération de la carte
plot <- ggplot() +
  geom_sf(data = map_data, aes(fill = .data[[mapped_var]])) +
  scale_fill_viridis_c(name = mapped_var_name, labels = scales::percent_format(scale = 100)) +
  ggtitle(paste(title)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = font_size),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.title.position = "plot",
        legend.title = element_text(size = font_size * 0.8),
        legend.text = element_text(size = font_size * 0.7))

# Enregistrement et nettoyage
ggsave(output_file, plot = plot, width = base_width, height = base_height, units = "in")
rm(aspect_ratio, base_height, base_width, bbox, font_size, mapped_var, mapped_var_name, plot)
```

**Cartes dynamiques**

```{r}
# Carte dynamique avec mapview, réduite à un département (les détails s'affichent en cliquant sur une commune).
subset_map_data <- map_data[map_data$dep == "2A", ]
subset_map_data$rounded_part <- paste0(round(100 * subset_map_data$part, digits = 2), " %")

popup_content <- paste("<strong>Commune</strong>", subset_map_data$NOM, sep = "<br>",
                       "<strong>Participation</strong>", subset_map_data$rounded_part, ""
                       )

mapview(subset_map_data, zcol = "rounded_part", popup = popup_content, layer.name = "Participation T1 1981")

rm(subset_map_data, popup_content)
```

```{r}
# Carte dynamique avec mapview (les détails s'affichent en cliquant sur une commune).
# Ne parvient jamais à se charger complètement, demande trop de ressources ?
map_data$rounded_part <- paste0(round(100 * map_data$part, digits = 2), " %")

popup_content <- paste("<strong>Commune</strong>", map_data$NOM, sep = "<br>",
                       "<strong>Participation</strong>", map_data$rounded_part, ""
                       )

mapview(map_data, zcol = "rounded_part", popup = popup_content, layer.name = "Participation T1 1981")

rm(subset_map_data, popup_content)
```
